name: Release

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
            GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Trigger publish workflow
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const version = require('./package.json').version;
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish.yml',
              ref: 'main',
              inputs: {
                version: version
              }
            });

      - name: Create draft branch
        if: success()
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            npm version prepatch --no-git-tag --preid="draft"
            DRAFT_VERSION=$(node -p "require('./package.json').version")
            
            git checkout -b ${DRAFT_VERSION}
            git add .
            git commit -m "chore(${DRAFT_VERSION}): prepare for next development iteration"
            git push https://${{ secrets.X_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${DRAFT_VERSION}
